[package]
name = "rust-lib-asm"
version = "0.1.0"
edition = "2021"
authors = ["Marc Beck KÃ¶nig <mbkj@tutamail.com>"]
rust-version = "1.74"
description = "Assembly comparisons for Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
